<<<<<<< HEAD
CRITICAL - 2021-12-19 22:04:57 --> Maximum execution time of 60 seconds exceeded
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-19 22:10:47 --> Maximum execution time of 60 seconds exceeded
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-12-19 22:14:20 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-12-19 22:14:20 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\siakad\app\Models\Mdl_auth.php(13): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\siakad\app\Controllers\Auth.php(53): App\Models\Mdl_auth->login_user('Admin', 'Admin')
#4 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(824): App\Controllers\Auth->cek_login()
#5 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\siakad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#9 {main}
ERROR - 2021-12-19 22:15:50 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-12-19 22:15:50 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\siakad\app\Models\Mdl_auth.php(13): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\siakad\app\Controllers\Auth.php(53): App\Models\Mdl_auth->login_user('Admin', 'admin')
#4 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(824): App\Controllers\Auth->cek_login()
#5 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\siakad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#9 {main}
ERROR - 2021-12-19 22:16:53 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-12-19 22:16:53 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\siakad\app\Models\Mdl_auth.php(13): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\siakad\app\Controllers\Auth.php(53): App\Models\Mdl_auth->login_user('Admin', 'aDMIN')
#4 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(824): App\Controllers\Auth->cek_login()
#5 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\siakad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#9 {main}
ERROR - 2021-12-19 22:17:55 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-12-19 22:17:55 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\siakad\app\Models\Mdl_auth.php(13): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\siakad\app\Controllers\Auth.php(53): App\Models\Mdl_auth->login_user('Admin', 'Admin')
#4 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(824): App\Controllers\Auth->cek_login()
#5 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\siakad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#9 {main}
ERROR - 2021-12-19 22:20:30 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2021-12-19 22:20:30 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\siakad\app\Models\Mdl_auth.php(13): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\siakad\app\Controllers\Auth.php(53): App\Models\Mdl_auth->login_user('admin', 'admin')
#4 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(824): App\Controllers\Auth->cek_login()
#5 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\siakad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#9 {main}
=======
CRITICAL - 2021-12-19 22:57:05 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\siakad\app\Views\admin\v_ta.php(38): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 38, Array)
#1 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Common.php(1097): CodeIgniter\View\View->render('admin/v_Ta', Array, true)
#4 C:\xampp\htdocs\siakad\app\Views\layout\v_content.php(4): view('admin/v_Ta')
#5 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Common.php(1097): CodeIgniter\View\View->render('layout/v_conten...', Array, true)
#8 C:\xampp\htdocs\siakad\app\Views\layout\v_wrapper.php(6): view('layout/v_conten...')
#9 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#10 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#11 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Common.php(1097): CodeIgniter\View\View->render('layout/v_wrappe...', Array, true)
#12 C:\xampp\htdocs\siakad\app\Controllers\Ta.php(13): view('layout/v_wrappe...', Array)
#13 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(824): App\Controllers\Ta->index()
#14 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ta))
#15 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 C:\xampp\htdocs\siakad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#17 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#18 {main}
CRITICAL - 2021-12-19 22:58:14 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\siakad\app\Views\admin\v_ta.php(38): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 38, Array)
#1 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Common.php(1097): CodeIgniter\View\View->render('admin/v_Ta', Array, true)
#4 C:\xampp\htdocs\siakad\app\Views\layout\v_content.php(4): view('admin/v_Ta')
#5 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Common.php(1097): CodeIgniter\View\View->render('layout/v_conten...', Array, true)
#8 C:\xampp\htdocs\siakad\app\Views\layout\v_wrapper.php(6): view('layout/v_conten...')
#9 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#10 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#11 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Common.php(1097): CodeIgniter\View\View->render('layout/v_wrappe...', Array, true)
#12 C:\xampp\htdocs\siakad\app\Controllers\Ta.php(13): view('layout/v_wrappe...', Array)
#13 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(824): App\Controllers\Ta->index()
#14 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ta))
#15 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 C:\xampp\htdocs\siakad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#17 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#18 {main}
CRITICAL - 2021-12-19 22:58:28 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\siakad\app\Views\admin\v_ta.php(38): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 38, Array)
#1 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Common.php(1097): CodeIgniter\View\View->render('admin/v_Ta', Array, true)
#4 C:\xampp\htdocs\siakad\app\Views\layout\v_content.php(4): view('admin/v_Ta')
#5 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Common.php(1097): CodeIgniter\View\View->render('layout/v_conten...', Array, true)
#8 C:\xampp\htdocs\siakad\app\Views\layout\v_wrapper.php(6): view('layout/v_conten...')
#9 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#10 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#11 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Common.php(1097): CodeIgniter\View\View->render('layout/v_wrappe...', Array, true)
#12 C:\xampp\htdocs\siakad\app\Controllers\Ta.php(13): view('layout/v_wrappe...', Array)
#13 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(824): App\Controllers\Ta->index()
#14 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ta))
#15 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 C:\xampp\htdocs\siakad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#17 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#18 {main}
CRITICAL - 2021-12-19 22:58:34 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\siakad\app\Views\admin\v_ta.php(38): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 38, Array)
#1 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Common.php(1097): CodeIgniter\View\View->render('admin/v_Ta', Array, true)
#4 C:\xampp\htdocs\siakad\app\Views\layout\v_content.php(4): view('admin/v_Ta')
#5 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Common.php(1097): CodeIgniter\View\View->render('layout/v_conten...', Array, true)
#8 C:\xampp\htdocs\siakad\app\Views\layout\v_wrapper.php(6): view('layout/v_conten...')
#9 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#10 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#11 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Common.php(1097): CodeIgniter\View\View->render('layout/v_wrappe...', Array, true)
#12 C:\xampp\htdocs\siakad\app\Controllers\Ta.php(13): view('layout/v_wrappe...', Array)
#13 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(824): App\Controllers\Ta->index()
#14 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ta))
#15 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 C:\xampp\htdocs\siakad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#17 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#18 {main}
CRITICAL - 2021-12-19 22:58:46 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\siakad\app\Views\admin\v_ta.php(38): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 38, Array)
#1 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Common.php(1097): CodeIgniter\View\View->render('admin/v_Ta', Array, true)
#4 C:\xampp\htdocs\siakad\app\Views\layout\v_content.php(4): view('admin/v_Ta')
#5 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Common.php(1097): CodeIgniter\View\View->render('layout/v_conten...', Array, true)
#8 C:\xampp\htdocs\siakad\app\Views\layout\v_wrapper.php(6): view('layout/v_conten...')
#9 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#10 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#11 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Common.php(1097): CodeIgniter\View\View->render('layout/v_wrappe...', Array, true)
#12 C:\xampp\htdocs\siakad\app\Controllers\Ta.php(13): view('layout/v_wrappe...', Array)
#13 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(824): App\Controllers\Ta->index()
#14 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ta))
#15 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 C:\xampp\htdocs\siakad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#17 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#18 {main}
ERROR - 2021-12-19 23:46:46 --> Unknown column 'id_gedung' in 'order clause'
CRITICAL - 2021-12-19 23:46:46 --> Call to a member function getResultArray() on bool
#0 C:\xampp\htdocs\siakad\app\Controllers\Ta.php(18): App\Models\Mdl_Ta->allData()
#1 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(824): App\Controllers\Ta->index()
#2 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ta))
#3 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\siakad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
ERROR - 2021-12-19 23:46:47 --> Unknown column 'id_gedung' in 'order clause'
CRITICAL - 2021-12-19 23:46:47 --> Call to a member function getResultArray() on bool
#0 C:\xampp\htdocs\siakad\app\Controllers\Ta.php(18): App\Models\Mdl_Ta->allData()
#1 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(824): App\Controllers\Ta->index()
#2 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ta))
#3 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\siakad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
ERROR - 2021-12-19 23:47:31 --> Unknown column 'id_gedung' in 'order clause'
CRITICAL - 2021-12-19 23:47:31 --> Call to a member function getResultArray() on bool
#0 C:\xampp\htdocs\siakad\app\Controllers\Ta.php(18): App\Models\Mdl_Ta->allData()
#1 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(824): App\Controllers\Ta->index()
#2 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ta))
#3 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\siakad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
ERROR - 2021-12-19 23:47:52 --> Unknown column 'id_gedung' in 'order clause'
CRITICAL - 2021-12-19 23:47:52 --> Call to a member function getResultArray() on bool
#0 C:\xampp\htdocs\siakad\app\Controllers\Ta.php(18): App\Models\Mdl_Ta->allData()
#1 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(824): App\Controllers\Ta->index()
#2 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ta))
#3 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\siakad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
ERROR - 2021-12-19 23:50:40 --> Unknown column 'id_gedung' in 'order clause'
CRITICAL - 2021-12-19 23:50:40 --> Call to a member function getResultArray() on bool
#0 C:\xampp\htdocs\siakad\app\Controllers\Ta.php(18): App\Models\Mdl_Ta->allData()
#1 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(824): App\Controllers\Ta->index()
#2 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ta))
#3 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\siakad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2021-12-19 23:55:05 --> Call to a member function allData() on null
#0 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(824): App\Controllers\Ta->index()
#1 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ta))
#2 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\siakad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\siakad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
>>>>>>> b4febc02b9ec60c69a55e1e31ac5f3d64f29c3ee
